name: polynote
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - numpy
  - matplotlib
  - pandas
  - bokeh
  - notebook>=5.2.2
  - ipywidgets>=6.0.1
  - ipython>=7.5.0
  - jedi
  - pyspark
  - virtualenv
  - jupyter-server-proxy
  - pip
  - openjdk=8
  - pip:
    - black
    - jep
